services:
  api:
    build: ""
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
  db:
    image: mariadb
    container_name: mariadb
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: books_store
      DB_PORT: 3306
      DB_HOST: 127.0.0.1
    ports:
    - "3306:3306"
