services:
  api:
    container_name: books_store
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    ports:
        - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      SQLALCHEMY_TRACK_MODIFICATIONS: 0